version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: jwks-rsa
    versions:
    - 1.12.3
    - 2.0.1
    - 2.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: mongodb
    versions:
    - 3.6.4
    - 3.6.5
  - dependency-name: knex
    versions:
    - 0.21.17
    - 0.21.18
    - 0.95.1
    - 0.95.2
