FROM node:14.15.0-alpine3.12

ENV PORT 3002
ENV HOST_R localhost:3005
ENV HOST_MONGO localhost:27017
ENV CONFIGPATH './config/config.js'
ENV MONGO_DB spip

WORKDIR /spip-api
EXPOSE ${PORT}
RUN npm install -g nodemon
CMD ["nodemon", "-r", "esm", "./server.js"]