version: "3.8"

services:
  mongo:
    image: mongo:4.4.1-bionic
    volumes:
      - mongo-data:/data/db

  api:
    image: spip-api-dev
    environment:
      - PORT=3002
      - HOST_R=http://rserver:3005/
      - HOST_MONGO=mongo
    volumes:
      - .:/spip-api
      - ./config-dev:/spip-api/config
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
