import * as persoonsgegevens from '../data-structures/nodes-persoonsgegevens.js'
import * as banenWoon from '../data-structures/nodes-banen-woon.js'
import * as banenWerk from '../data-structures/nodes-banen-werk.js'
import * as persoonsgegevens2015 from '../data-structures/nodes-persoonsgegevens-2015.js'
import * as banenWoon2015 from '../data-structures/nodes-banen-woon-2015.js'
import * as banenWerk2015 from '../data-structures/nodes-banen-werk-2015.js'
import * as banenSBI2015 from '../data-structures/nodes-banen-sbi-2015.js'
import * as squareKilometers from '../data-structures/nodes-square-kms.js'
import * as persoonsgegevens2016 from '../data-structures/nodes-persoonsgegevens-2016.js'
import * as banenWoon2016 from '../data-structures/nodes-banen-woon-2016.js'
import * as banenWerk2016 from '../data-structures/nodes-banen-werk-2016.js'
import * as banenWoonZorg from '../data-structures/nodes-banen-woon-zorg.js'
import * as banenWerkZorg from '../data-structures/nodes-banen-werk-zorg.js'

// TODO